### PR TITLE
Readying loggerator & adding rails glue

### PR DESCRIPTION
**Pull request by reidmix**
This is a work in progress.  

Added so far:
- moved and messaged some of the original lib 
- added glue to load loggerator in Rails
- added (Librato) `Metrics` helper (from Laika)
- added `Namespace` helper (from Laika)

Todo:
- [x] Add generator for Loggerator intializer
- [x] Consider renaming `log_context` to `request_context`
- [x] Consider renaming `context` to `log_context` to avoid name collisions
- [x] Consider renaming `log_exception` to `log_error` because it's shorter
- [x] Determine how to turn logging of for tests (and mechanism to switch on/off)

In later PR: 
- `loggerator/sinatra` include loggerator into Sinatra apps
- Provide a mechanism to silence the logs?
- Add documentation on how load Loggerator in rails
- Add documentation on how to user `log`, `log_error` and `log_context`
- Add documentation on how to use `Metrics`
- Add documentation on how to use `Namespace`
- Write and update specs

### CODE REVIEW

**Comment by jmervine** [comment]
@reidmix 

RE Todos:

- +1 on renaming `log_context` to `request_context`
- +1 on renaming `context` to `log_context`


What can we do here to get this moving. Mind if I start tinkering on this branch.

**Comment by reidmix** [comment]
@jmervine obtw, i don't mind, feel free to tinker too.

**Comment by reidmix** [comment]
This should define the first pass on loggerator, it has all the basic functionality.
Future PRs will have docs, better specs, sinatra integration.

**Comment by jmervine** [comment]
👍 This all looks good. What do you think's left before shipping the gem? And do you want to ship this one?

**Comment by reidmix** [comment]
I wish it had more complete tests, but honestly I want to move back to rspec and reorganize things.  So that's more tests and docs, both of which are not needed for the gem to "work".

**Comment by reidmix** [comment]
Yeah I can ship it \o/ I have to remember how.

**Comment by jmervine** [comment]
```
gem install gemcutter
gem build <gemspec>
gem push <gem name>
```

**Comment by reidmix** [comment]
Thanks for the instructions -- going ahead and merging and cutting the gem.

**Pull request merged**
